### ISSUE TITLE
GUI overhaul

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#307]
## New Ideas will be in the next Epic found here #360

- [x] cleanup JS -> rebuilt in vue.js - WIP
- [x] more functions behind login, including a way to logout - WIP
-- [x] privacy:
--- [x] aliceWatch
--- [x] syslog
-- [x] administration:
--- [x] scenarios
--- [x] skills
--- [x] myHome editing mode
- [ ] device/location depending display
-- [x] start directly in theater mode
-- [x] use different widget layouts
-- [x] start in different widget layouts
-- [ ] widgets need site or at least widget instance dependent settings
-- [ ] screen privileges (what is the default user access level)
-- [ ] define uuid of the speaker/sat that should output voice (e.g. please log in) #251 
- [x] Central login function #337
- [x] myHome display mode as widget
-- [ ] only allow display and toggling devices
-- [ ] allow widget show on toggle (requires multiple instances of one widget)
- [x] small screen/touch interface
-- [x] left sidebar initially hidden. One button opens
-- [ ] bigger sidebar as overlay/dropdown
- [x] Fix z-Indexing for widgets #330
-- [ ] is now available as a generic z-indexed css class
- [x] multiple instances of one widget #331 - WIP
-- [x] way to init. widgets has to change
-- [x] data of widgets has to be saved separately
-- [x] adding of widgets needs changed menu
~~- [ ] parenting of widgets - not planned at the moment, lowest priority
-- [ ] of bigger use when you have a big myHome widget on the lower layer and special widgets above for e.g. room temperature
-- moved to long-term #360~~
- [ ] MyHome documentation - WIP
- [x] MyHome fallback for missing Icons
-- [x] If an icon can't be loaded, fall back to a generic "error Icon" -> easier to debug
- [x] MyHome spawn voice created room in a more convenient size and location
- [x] MyHome nested rooms
- [x] MyHome - Renaming a device does not rename it in configs
- [x] MyHome - find a good way to "magnetize" movement and resizing -> vue?
- [x] "Alice currently not available" must not reload the page when stuff was changed (myHome, AdminConfig, widget movement..) - shouldn't be a problem with single page layout anymore!

## TODOs for Merge with b5
- [ ] update skills for new path to LocationManager and Location
- [ ] update skills with telemetry for storeData and siteId == deviceId
- [ ] update skills to new widget structure
- [ ] update skills for new DeviceType structure

**Comment by hipitihop** [comment]
I'd like to add a proposal to the list, consider using React
https://reactjs.org/tutorial/tutorial.html#what-is-react

**Comment by Psychokiller1888** [comment]
Re parenting... ATM I did not do it as this can easily go down a rabbit hole. We'll see if I get an idea

Now, re multi instances. It basically completly works as of now BUT... Javascript.... Where styles can be "scoped" to their parent div and not override same named classes. JS cannot. That means, on the same page, if you have twice the "time" widget active, only one will work, because well... They use the same target ids, the same function names etc etc and are loaded twice. This is really really problematic. One thing could be made core side though....

- When Alice imports the widgets
   - MD5 hash of the untouched file
   - Keep hashes in a file
   - If no modded files exist OR file hash has changed
      - Check html files for
         - `id="my_id"`
         - List those ids and rename them to `id="uuid4()_my_id"`
      - Check JS files for:
         - ID selectors => rename them according to above list
         - Function definitions => rename them to `uuid4()_functionName`
         - Check refs for those functions and rename accordingly
         - Constants => rename them to `uuid4_constantName`
         - Check refs for those constants and rename accordingly
      - CSS can be left alone, it is anyway scoped to the <widget> tag
      - Dump the new files into `prod_widgetName.widget/js` files
      - Serve modded files
   - If modded file exists and hash not changed serve the modded files

Question is, what do I forget?

**Comment by Psychokiller1888** [comment]
> I'd like to add a proposal to the list, consider using React
> https://reactjs.org/tutorial/tutorial.html#what-is-react

Went for Vue.js

**Comment by LazzaAU** [comment]
### *Observations noticed while testing the new interface. (viewed on firefox)*

1.
- [ ] miss alignment of headings in some of the "admin" interface. refer this following screenshot.

![Kazam_screenshot_00044](https://user-images.githubusercontent.com/31381872/100678514-12a98d00-33b9-11eb-9804-bbc80453ad29.png)


2. The following buttons seem to of stopped working in the skills tab

- [ ] Stop
- [ ] Reload
- [ ] Remove

Settings button works. The following is in the console , can expand any relevant error if required. 

![Kazam_screenshot_00046](https://user-images.githubusercontent.com/31381872/100674982-d0308200-33b1-11eb-8700-b9963d21e7e0.png)

**Comment by LazzaAU** [comment]
i can confirm the three buttons work in the skill tab again.

Clicking the "stop" button then refreshing the page takes the skill out of alphabetical order and places it to the bottom of the page. If your unaware of this new shift ( as in someone like me with a small screen that has to scroll) then you may deem it to be broken cause the skill disappears. When in fact it hasn't its just moved

Starting the skill again does not move it back to alphabetical order where you are used to it being. unless you restart

- [ ] Confirmed
- [ ] fixed
- [ ] Doesn't need fixed. That's how it is.

![skillOrder](https://user-images.githubusercontent.com/31381872/100828352-a9a24200-34aa-11eb-84a1-fc2f9ef7f247.gif)

**Comment by LazzaAU** [comment]
and sorry if i'm jumping ahead of things here but assume your aware of this also 

- [ ] WIP
- [ ] Fixed

![delete skill](https://user-images.githubusercontent.com/31381872/100829218-9001fa00-34ac-11eb-9dc5-b3136ccd7493.gif)

**Comment by philipp2310** [comment]
- [ ] newly installed skills are only shown after reloading the skill page

**Comment by Psychokiller1888** [comment]
Devices are grouped by skills, with html dropdown list titles

**Comment by Psychokiller1888** [comment]
Re `myHome: Linking starts, but no connection from AliceCore to a room is possible: red border, no error message on click`

On your screenshot it looks like Alice isn't placed in a location?

**Comment by Psychokiller1888** [comment]
Yes, because there's no room by default instead of Hive as you had. Maybe we shouldn't display Alice until there's a room created by the user and automatically add Alice to that location?

**Comment by Psychokiller1888** [comment]
Or auto create the first location as you did

**Comment by philipp2310** [comment]
Should be easily done by just adding it initially to room 1 (just deleted my room with alice inside, added a new one and alice appeared in it)

**Comment by Psychokiller1888** [comment]
true

**Comment by Psychokiller1888** [comment]
Uninstall skill will reappear in shop after the shop data has been fetched again`. Core checks every 15 minutes, and UI asks core store data every 5 minutes. I'm hesitating to trigger a store update after a skill deletion, because if a user delete 5 skills in a row, that's 5 store refresh. Thoughts?

**Comment by Psychokiller1888** [comment]
Re widgets page bug after changing main page, I honestly have no freaking idea why this happens. Added logs, the activeTabId is always correct, but the wrong class is applied to the tab

**Comment by philipp2310** [comment]
> Uninstall skill will reappear in shop [...] 

In my case it was the broken zigbee stick -> "Let's try reinstalling zigbee2mqtt"
How about a "dirty"-flag when you uninstall, that will force a UI reload of the store even if the 5 min aren't passed yet? That shouldn't trigger too often - unless the user really uninstalls one skill -> store -> uninstall next skill -> store...
Core store refresh every 15 minutes is more than enough, I wouldn't touch that.

**Comment by Psychokiller1888** [comment]
Yeah, did not think about re installing case... We could maybe also use the "skill deleted" mqtt topic and re add the skill in the store, simply?

**Comment by Psychokiller1888** [comment]
Re finding the center of floorplan, I started to add an arrow that will show the center of the map. And when you click it the map is reset to center with 1.0 zoom. I also added floorplan position and zoom saving

**Comment by LazzaAU** [comment]
New Interface Feature ? - **Voice selection**.

Not sure if this is already added or in the pipeline, but i'd like to suggest 

- Having a drop down list in Admin screen, for TTS voice

.
This would later allow a user to select a TTS voice from a drop down list for the appropriate engine selected.

**Comment by Psychokiller1888** [comment]
Yep, wanted that since long

**Comment by Psychokiller1888** [comment]
Can't repro the `prevent redundant navigation`

**Comment by philipp2310** [comment]
prevent redundant navigation: just a cosmetic thing, not blocking the merge - I'll take a look after work :)

.then() for admin utils restart contains the switch to syslog - if you switch manually to syslog before the promise is fulfilled, you get the double navigation.

At least that is what I read out of the constellation (was repeatable for me) - if it is true, I should be able to fix it later ^^

**Comment by Psychokiller1888** [comment]
Oh, ok, when coming from admin that auto leads to syslog, then I get it

**Comment by Psychokiller1888** [comment]
Good if we get rid of them, but I think you don't see those messages in production mode, once built

**Comment by LazzaAU** [comment]
Have started a thread for observations and bugs noticed with the merged new-interface. Issue #369

**Comment by philipp2310** [comment]
Closing this issue and collecting any open points from this issue in the corresponding topics.
Awesome job! The new interface feels so good :)
