### ISSUE TITLE
Auto download skills for unsupported intents

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#313]
We need to handle not recognized intents a bit differently and try to propose the user, automatically, a skill download for the intent he tried to use. The idea is to propose a seamless experience to users. Because technically, Alice would know what to do if the proper skill was installed.

The flow that I can imagine would be something like:

- Hey Alice
- Yes?
- What the stockmarket price of oil this morning?
   - **Alt 1, only one skill**
      - I'm sorry, I don't understand what you want. But hey, I might if you allow me to download the "Stock market" skill! Do you allow me?
         - **Accept**
            - Yes
            - Ok, downloading...
            - ...
            - The stock market price of oil is currently 0.01 usd per barel.
         - **Refuse**
            - Ok, so I can't tell, sorry
   - **Alt 2, more than one skill**
      - I'm sorry, I don't understand what you want. But hey, I might if you allow me to download a skill. I have found 2 skills: `Stock Market` by Psycho and `Yandex` by Philipp. Can I install one? If yes, which one?
         - **Accept**
            - Yandex
            - Ok, downloading...
            - ...
            - The stock market price of oil is currently 5'000'000 roubles per barel.
         - **Refuse**
            - Ok, so I can't tell, sorry

That would mean the following:

- [x] Alice needs to be online
- [x] Skills need to have a `speakableName` field in the installer, because as of now they are PascalCase which might sound weird
- [x] Alice needs to know what the available skills can do
   - [x] Skill intents would require a field that proposes 2 or 3 max utterances, called something like `mostCommonWayToAsk`, that Alice can read when checking the store and compare the user's request to, in order to propose relevant skills
